const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('sidenotch', {
  getSettings: () => ipcRenderer.invoke('settings:get'),
  saveSettings: (patch) => ipcRenderer.invoke('settings:save', patch),
  getUsage: () => ipcRenderer.invoke('usage:get'),
  refresh: () => ipcRenderer.invoke('usage:refresh'),
  getDisplays: () => ipcRenderer.invoke('displays:get'),
  setIgnoreMouse: (v) => ipcRenderer.send('bar:ignore-mouse', v),
  setBarHeight: (h) => ipcRenderer.send('bar:height', h),
  setFocusable: (v) => ipcRenderer.send('bar:focusable', v),
  drag: (phase) => ipcRenderer.send('bar:drag', phase),
  openSettings: () => ipcRenderer.send('app:open-settings'),
  openUrl: (u) => ipcRenderer.send('app:open-url', u),
  quit: () => ipcRenderer.send('app:quit'),
  getApprovals: () => ipcRenderer.invoke('approvals:get'),
  decide: (id, decision, extra) => ipcRenderer.invoke('approvals:decide', id, decision, extra || {}),
  installHook: () => ipcRenderer.invoke('approvals:install-hook'),
  uninstallHook: () => ipcRenderer.invoke('approvals:uninstall-hook'),
  dismiss: (id) => ipcRenderer.invoke('feed:dismiss', id),
  maestriPair: (opts) => ipcRenderer.invoke('maestri:pair', opts),
  maestriUnpair: () => ipcRenderer.invoke('maestri:unpair'),
  maestriAction: (id, action, text) => ipcRenderer.invoke('maestri:action', id, action, text),
  setDnd: (v) => ipcRenderer.invoke('dnd:set', v),
  getUpdate: () => ipcRenderer.invoke('update:get'),
  checkUpdate: () => ipcRenderer.invoke('update:check'),
  downloadUpdate: () => ipcRenderer.invoke('update:download'),
  installUpdate: () => ipcRenderer.invoke('update:install'),
  onApprovals: (cb) => ipcRenderer.on('approvals', (_e, d) => cb(d)),
  onNotify: (cb) => ipcRenderer.on('notify', (_e, d) => cb(d)),
  onUpdate: (cb) => ipcRenderer.on('update', (_e, d) => cb(d)),
  onUsage: (cb) => ipcRenderer.on('usage', (_e, d) => cb(d)),
  onSettings: (cb) => ipcRenderer.on('settings', (_e, d) => cb(d)),
  onBar: (cb) => { for (const ch of ['bar:open', 'bar:toggle', 'bar:blur']) ipcRenderer.on(ch, () => cb(ch.split(':')[1])); }
});
